# Create Train and Test Dataset

Since the creation of the dataset takes a lot of time because of the large amount of data, the API for the dollar/peso conversion and the encoder, we will create the datasets in this notebook and store it

In [ ]:
import pandas as pd
import pickle
from challenge.new_or_used import build_dataset
from challenge.dataset.preprocess import preprocess_whole_dataset


X_train, y_train, X_test, y_test = build_dataset()


df = pd.DataFrame(X_train)
df.head()

/Users/catalinatrujillo/Downloads/MELI_Challenge/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

,seller_address,warranty,sub_status,deal_ids,base_price,shipping,non_mercado_pago_payment_methods,seller_id,variations,site_id,...,stop_time,status,video_id,catalog_product_id,subtitle,initial_quantity,start_time,permalink,sold_quantity,available_quantity
0,"{'country': {'name': 'Argentina', 'id': 'AR'},...",None,[],[],80.0,"{'local_pick_up': True, 'methods': [], 'tags':...","[{'description': 'Transferencia bancaria', 'id...",8208882349,[],MLA,...,1446669773000,active,None,NaN,None,1,1441485773000,http://articulo.mercadolibre.com.ar/MLA4695330...,0,1
1,"{'country': {'name': 'Argentina', 'id': 'AR'},...",NUESTRA REPUTACION,[],[],2650.0,"{'local_pick_up': True, 'methods': [], 'tags':...","[{'description': 'Transferencia bancaria', 'id...",8141699488,[],MLA,...,1448474910000,active,None,NaN,None,1,1443290910000,http://articulo.mercadolibre.com.ar/MLA7160447...,0,1
2,"{'country': {'name': 'Argentina', 'id': 'AR'},...",None,[],[],60.0,"{'local_pick_up': True, 'methods': [], 'tags':...","[{'description': 'Transferencia bancaria', 'id...",8386096505,[],MLA,...,1447027027000,active,None,NaN,None,1,1441843027000,http://articulo.mercadolibre.com.ar/MLA7367189...,0,1
3,"{'country': {'name': 'Argentina', 'id': 'AR'},...",None,[],[],580.0,"{'local_pick_up': True, 'methods': [], 'tags':...","[{'description': 'Transferencia bancaria', 'id...",5377752182,[],MLA,...,1449191596000,active,None,NaN,None,1,1443466076000,http://articulo.mercadolibre.com.ar/MLA9191625...,0,1
4,"{'country': {'name': 'Argentina', 'id': 'AR'},...",MI REPUTACION.,[],[],30.0,"{'local_pick_up': True, 'methods': [], 'tags':...","[{'description': 'Transferencia bancaria', 'id...",2938071313,[],MLA,...,1445638040000,active,None,NaN,None,1,1440454040000,http://articulo.mercadolibre.com.ar/MLA7787961...,0,1

In [2]:
X_df = preprocess_whole_dataset(df, use_encoders=True)
X_df.head()

Preprocessing seller info...
Preprocessing variations...
Preprocessing non mercado pago payments...
Preprocessing warranty...
Preprocessing shipping...
Preprocessing prices...
Preprocessing categories...
Preprocessing has parent item id...
Preprocessing pictures...
Preprocessing quantities...
Preprocessing attributes...
Preprocessing times...
Preprocessing title...

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‰| 5625/5626 [02:04<00:00, 45.34it/s]

,seller_address_state,most_used_seller_address_cities,most_new_seller_address_cities,seller_id,variations_amount_bin,variations_bin,tarjeta,transferencia_bancaria,acordar_comprador,num_payment_methods_non_mercadopago,...,title_home,title_electronics,title_nuevo_or_usado,total_time_seconds,kmeans_title_label_0,kmeans_title_label_1,kmeans_title_label_2,kmeans_title_label_3,kmeans_title_label_4,attributes_dflt
0,Capital Federal,False,False,other,"(-1, 0]","(-1, 0]",False,True,True,3,...,False,True,unknown,5.18400,False,False,True,False,False,False
1,Capital Federal,False,False,other,"(-1, 0]","(-1, 0]",False,True,False,2,...,True,False,unknown,5.18400,False,False,False,False,True,False
2,Capital Federal,False,False,other,"(-1, 0]","(-1, 0]",True,True,False,3,...,False,False,unknown,5.18400,False,False,False,True,False,False
3,Capital Federal,False,False,other,"(-1, 0]","(-1, 0]",True,True,False,3,...,False,False,unknown,5.72552,False,False,True,False,False,False
4,Buenos Aires,False,False,other,"(-1, 0]","(-1, 0]",False,True,True,3,...,False,False,unknown,5.18400,False,True,False,False,False,False

In [4]:
for col in X_df.columns:
    try:
        if X_df[col].dtype == "object":
            X_df[col] = X_df[col].astype("category")
    except:
        print(col)
X_df.dtypes

seller_address_state                   category
most_used_seller_address_cities            bool
most_new_seller_address_cities             bool
seller_id                              category
variations_amount_bin                  category
variations_bin                         category
tarjeta                                    bool
transferencia_bancaria                     bool
acordar_comprador                          bool
num_payment_methods_non_mercadopago       int64
efectivo                                   bool
warranty                               category
shipping_local_pick_up                     bool
shipping_free_shipping                     bool
shipping_method                        category
shipping_mode                          category
listing_type_id                        category
price_usd                               float64
buying_mode                            category
has_parent_item_id                         bool
popular_category                           bool
pictures_max_size                       float64
automatic_relist                           bool
initial_quantity                        float64
sold_quantity                           float64
available_quantity                      float64
title_sex_shop                             bool
title_car                                  bool
title_clothes                              bool
title_home                                 bool
title_electronics                          bool
title_nuevo_or_usado                   category
total_time_seconds                      float64
kmeans_title_label_0                       bool
kmeans_title_label_1                       bool
kmeans_title_label_2                       bool
kmeans_title_label_3                       bool
kmeans_title_label_4                       bool
attributes_dflt                            bool
dtype: object

In [ ]:
# Save the processed dataset into the data folder
with open("../data/train_dataset.pkl", "wb") as f:
    pickle.dump(X_df, f)

In [3]:
X_df_test = pd.DataFrame(X_test)
X_df_test = preprocess_whole_dataset(X_df_test, use_encoders=True)
for col in X_df_test.columns:
    try:
        if X_df_test[col].dtype == "object":
            X_df_test[col] = X_df_test[col].astype("category")
    except:
        print(col)
X_df_test.dtypes

Preprocessing seller info...
Preprocessing variations...
Preprocessing non mercado pago payments...
Preprocessing warranty...
Preprocessing shipping...
Preprocessing prices...
Preprocessing categories...
Preprocessing has parent item id...
Preprocessing pictures...
Preprocessing quantities...
Preprocessing attributes...
Preprocessing times...
Preprocessing title...

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‰| 625/626 [00:13<00:00, 44.74it/s]

seller_address_state                   category
most_used_seller_address_cities            bool
most_new_seller_address_cities             bool
seller_id                              category
variations_amount_bin                  category
variations_bin                         category
tarjeta                                    bool
transferencia_bancaria                     bool
acordar_comprador                          bool
num_payment_methods_non_mercadopago       int64
efectivo                                   bool
warranty                               category
shipping_local_pick_up                     bool
shipping_free_shipping                     bool
shipping_method                        category
shipping_mode                          category
listing_type_id                        category
price_usd                               float64
buying_mode                            category
has_parent_item_id                         bool
popular_category                           bool
pictures_max_size                       float64
automatic_relist                           bool
initial_quantity                        float64
sold_quantity                           float64
available_quantity                      float64
title_sex_shop                             bool
title_car                                  bool
title_clothes                              bool
title_home                                 bool
title_electronics                          bool
title_nuevo_or_usado                   category
total_time_seconds                      float64
kmeans_title_label_0                       bool
kmeans_title_label_1                       bool
kmeans_title_label_2                       bool
kmeans_title_label_3                       bool
kmeans_title_label_4                       bool
attributes_dflt                            bool
dtype: object

In [7]:
with open("../data/test_dataset.pkl", "wb") as f:
    pickle.dump(X_df_test, f)